# Generated by Django 2.1.3 on 2018-12-10 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BACK_OFFICE', 'back_office'), ('SALES_MARKETING', 'sales_marketing'), ('FRONT_OFFICE', 'front_office'), ('HOUSE_KEEPING', 'house_keeping'), ('FITNESS', 'fitness'), ('FOOD_BERVERAGE', 'food_berverage'), ('FINANCE', 'finance')], max_length=30, unique=True)),
                ('role', models.TextField()),
                ('tel_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Extracost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10000000)),
                ('payment_type', models.CharField(choices=[('CREDIT CARD', 'credit card'), ('DEBIT CARD', 'debit card'), ('CHEQUE', 'cheque'), ('CASH', 'cash')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guestcar',
            fields=[
                ('car_num', models.DecimalField(decimal_places=0, default='0', max_digits=10, primary_key='True', serialize=False)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('guest_class', models.CharField(choices=[('SILVER', 'silver'), ('GOLD', 'gold'), ('VIP', 'vip'), ('VVIP', 'vvip')], max_length=10, primary_key='True', serialize=False)),
                ('discount', models.CharField(default='0%', max_length=10)),
                ('cumulative_cost', models.DecimalField(decimal_places=0, default='0', max_digits=100000000)),
                ('reserve_count', models.DecimalField(decimal_places=0, default='0', max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('handle_or_not', models.DecimalField(choices=[(1, '미배정'), (2, '처리중'), (3, '처리완료')], decimal_places=0, default=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reserve_num', models.DecimalField(decimal_places=0, default=0, max_digits=5, primary_key='True', serialize=False)),
                ('cost', models.CharField(default=0, max_length=10000000)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('companion', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('room_floor', models.DecimalField(decimal_places=0, default='1', max_digits=1)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_num', models.DecimalField(decimal_places=0, max_digits=4, primary_key='True', serialize=False)),
                ('status_clean', models.CharField(choices=[('CLEAN', 'Clean'), ('UNCLEAN', 'Unclean')], default='CLEAN', max_length=10)),
                ('room_floor', models.DecimalField(decimal_places=0, default='1', max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key='True', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_first', models.CharField(max_length=2)),
                ('name_last', models.CharField(max_length=3)),
                ('work_start_time', models.DateTimeField(auto_now=True)),
                ('work_end_time', models.DateTimeField(auto_now=True)),
                ('work_weekday', models.CharField(max_length=3)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6)),
                ('status', models.CharField(choices=[('WORKING', 'working'), ('RESTING', 'resting'), ('HOLIDAY', 'holiday'), ('ABSENCE', 'absence')], max_length=7)),
                ('phone_num', models.CharField(max_length=13)),
                ('photo', models.ImageField(upload_to='images')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('room_type', models.CharField(choices=[('STANDARD SINGLE', 'Standard Single'), ('STANDARD DOUBLE', 'Standard Double'), ('SSTANDARD SUITE', 'Standard Suite')], default='SINGLE', max_length=20, primary_key='True', serialize=False)),
                ('capacity', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=10000000)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Type'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Room'),
        ),
        migrations.AddField(
            model_name='request_post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request_post',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Department'),
        ),
        migrations.AddField(
            model_name='request_post',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Guest'),
        ),
        migrations.AddField(
            model_name='request_post',
            name='room_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Room'),
        ),
        migrations.AddField(
            model_name='request_post',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
        migrations.AddField(
            model_name='extracost',
            name='reserve_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Reservation'),
        ),
        migrations.AddField(
            model_name='charge',
            name='room_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Room'),
        ),
        migrations.AddField(
            model_name='charge',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
    ]
