# Generated by Django 2.1.3 on 2018-12-06 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BACK_OFFICE', 'back_office'), ('SALES_MARKETING', 'sales_marketing'), ('FRONT_OFFICE', 'front_office'), ('HOUSE_KEEPING', 'house_keeping'), ('FITNESS', 'fitness'), ('FOOD_BERVERAGE', 'food_berverage'), ('FINANCE', 'finance')], max_length=30, unique=True)),
                ('role', models.TextField()),
                ('tel_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('handle_or_not', models.DecimalField(choices=[(1, '미배정'), (2, '처리중'), (3, '처리완료')], decimal_places=0, default=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_num', models.DecimalField(decimal_places=0, max_digits=4, primary_key='True', serialize=False)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('SUITE', 'Suite')], default='SINGLE', max_length=10)),
                ('status_clean', models.CharField(choices=[('CLEAN', 'Clean'), ('UNCLEAN', 'Unclean')], default='CLEAN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key='True', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_first', models.CharField(max_length=2)),
                ('name_last', models.CharField(max_length=3)),
                ('work_start_time', models.DateTimeField(auto_now=True)),
                ('work_end_time', models.DateTimeField(auto_now=True)),
                ('work_weekday', models.CharField(max_length=3)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6)),
                ('status', models.CharField(choices=[('WORKING', 'working'), ('RESTING', 'resting'), ('HOLIDAY', 'holiday'), ('ABSENCE', 'absence')], max_length=7)),
                ('phone_num', models.CharField(max_length=13)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Department')),
            ],
        ),
        migrations.AddField(
            model_name='request_post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request_post',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Department'),
        ),
        migrations.AddField(
            model_name='request_post',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Guest'),
        ),
        migrations.AddField(
            model_name='request_post',
            name='room_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Room'),
        ),
    ]
