# Generated by Django 2.1.3 on 2018-12-07 04:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reserve_num', models.DecimalField(decimal_places=0, default=0, max_digits=5, primary_key='True', serialize=False)),
                ('guest_id', models.CharField(default='', max_length=10)),
                ('cost', models.CharField(default=0, max_length=10000000)),
                ('date_start', models.CharField(default='0000-00-00', max_length=20)),
                ('date_end', models.CharField(default='0000-00-00', max_length=20)),
                ('book_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('companion', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('room_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Room')),
            ],
        ),
    ]
