# Generated by Django 2.1.3 on 2018-12-06 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key='True', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name_first', models.CharField(max_length=2)),
                ('name_last', models.CharField(max_length=3)),
                ('work_start_time', models.DateTimeField(auto_now=True)),
                ('work_end_time', models.DateTimeField(auto_now=True)),
                ('work_weekday', models.CharField(max_length=3)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6)),
                ('status', models.CharField(choices=[('WORKING', 'working'), ('RESTING', 'resting'), ('HOLIDAY', 'holiday'), ('ABSENCE', 'absence')], max_length=7)),
                ('phone_num', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_floor',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=1),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('BACK_OFFICE', 'back_office'), ('SALES_MARKETING', 'sales_marketing'), ('FRONT_OFFICE', 'front_office'), ('HOUSE_KEEPING', 'house_keeping'), ('FITNESS', 'fitness'), ('FOOD_BERVERAGE', 'food_berverage'), ('FINANCE', 'finance')], max_length=30),
        ),
        migrations.AddField(
            model_name='staff',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Department'),
        ),
    ]
