# Generated by Django 2.1.3 on 2018-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20181128_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key='True', serialize=False)),
                ('name_first', models.CharField(max_length=2)),
                ('name_last', models.CharField(max_length=3)),
                ('work_start_time', models.DateTimeField(auto_now=True)),
                ('work_end_time', models.DateTimeField(auto_now=True)),
                ('work_weekday', models.CharField(max_length=3)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6)),
                ('status', models.CharField(choices=[('WORKING', 'working'), ('RESTING', 'resting'), ('HOLIDAY', 'holiday'), ('ABSENCE', 'absence')], max_length=7)),
                ('phone_num', models.CharField(max_length=13)),
                ('dept', models.CharField(choices=[('BACK_OFFICE', 'back_office'), ('SALES_MARKETING', 'sales_marketing'), ('FRONT_OFFICE', 'front_office'), ('HOUSE_KEEPING', 'house_keeping'), ('FITNESS', 'fitness'), ('FOOD_BERVERAGE', 'food_berverage'), ('FINANCE', 'finance')], max_length=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('SUITE', 'Suite')], default='SINGLE', max_length=10),
        ),
    ]
