# Generated by Django 2.1.3 on 2018-12-04 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0007_auto_20181203_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name_first',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name_last',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key='True', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
