# Generated by Django 2.1.3 on 2018-12-05 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key='True', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('guest_pw', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('sex', models.CharField(max_length=1)),
                ('phone_num', models.CharField(max_length=13)),
                ('language', models.CharField(max_length=20)),
                ('guest_class', models.CharField(max_length=10)),
            ],
        ),
    ]
