# Generated by Django 2.1.3 on 2018-12-05 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('sex', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6)),
                ('phone_num', models.CharField(max_length=13)),
                ('e_mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(max_length=20)),
                ('guest_class', models.CharField(max_length=10)),
            ],
        ),
    ]
